# Generated by Django 3.2.6 on 2021-10-22 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id_bairro', models.AutoField(db_column='ID_BAIRRO', primary_key=True, serialize=False)),
                ('nome_bairro', models.CharField(db_column='NOME_BAIRRO', max_length=50, unique=True)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('taxa', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TB_BAIRRO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(db_column='NOME_CATEGORIA', max_length=50)),
                ('ativo', models.BooleanField()),
            ],
            options={
                'db_table': 'TB_CATEGORIA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.ForeignKey(blank=True, db_column='bairro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Gerenciamento.bairro')),
            ],
            options={
                'db_table': 'TB_ENDERECO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(db_column='ID_INGREDIENTE', primary_key=True, serialize=False)),
                ('nome_ingrediente', models.CharField(db_column='NOME_INGREDIENTE', max_length=50)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'TB_INGREDIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TB_USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Gerenciamento.usuario')),
                ('nome_cliente', models.CharField(db_column='NOME_CLIENTE', max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'TB_CLIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.OneToOneField(db_column='id_funcionario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Gerenciamento.usuario')),
                ('cargo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TB_FUNCIONARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(db_column='ID_PRODUTO', primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('descricao', models.CharField(blank=True, max_length=400, null=True)),
                ('ativo', models.BooleanField()),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Gerenciamento.categoria')),
                ('ingredientes', models.ManyToManyField(to='Gerenciamento.Ingrediente')),
            ],
            options={
                'db_table': 'TB_PRODUTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='ID_PEDIDO', primary_key=True, serialize=False)),
                ('codigo_pedido', models.CharField(blank=True, max_length=8, null=True)),
                ('atendimento_presencial', models.BooleanField()),
                ('valor_total', models.FloatField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField()),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('tipo_pedido', models.CharField(blank=True, db_column='TIPO_PEDIDO', max_length=10, null=True)),
                ('endereco', models.ForeignKey(blank=True, db_column='endereco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Gerenciamento.endereco')),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Gerenciamento.cliente')),
                ('funcionario', models.ForeignKey(blank=True, db_column='funcionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Gerenciamento.funcionario')),
            ],
            options={
                'db_table': 'TB_PEDIDO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_item_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
                ('confirmado', models.IntegerField(blank=True, db_column='CONFIRMADO', null=True)),
                ('pedido', models.ForeignKey(blank=True, db_column='pedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Gerenciamento.pedido')),
                ('produto', models.ForeignKey(db_column='produto', on_delete=django.db.models.deletion.DO_NOTHING, to='Gerenciamento.produto')),
            ],
            options={
                'db_table': 'TB_ITEM_PEDIDO',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='Gerenciamento.cliente'),
        ),
    ]
