# Generated by Django 3.2.6 on 2021-09-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbbairro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbcategoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbcliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbendereco',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbfuncionario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbingrediente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbingredienteproduto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbitempedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbpedido',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbproduto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tbusuario',
            options={},
        ),
    ]
